# Generated by Django 5.0.1 on 2025-12-23 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name or title of the contract', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the contract', null=True)),
                ('file', models.FileField(help_text='Upload PDF or DOCX contract file', upload_to='contracts/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size of the file in bytes')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], help_text='Type of the uploaded file', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='uploaded', help_text='Current status of the contract analysis', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the contract was uploaded')),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='When the analysis was completed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this contract was updated')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from the contract document', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
