# Generated by Django 5.0.1 on 2025-12-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the file in bytes (auto-calculated from uploaded file)', null=True),
        ),
    ]
