# Generated by Django 5.0.1 on 2025-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata about the analysis (model used, timestamp, processing time, etc.)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='analysis_summary',
            field=models.TextField(blank=True, help_text='AI-generated executive summary of the contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='extracted_clauses',
            field=models.JSONField(blank=True, default=list, help_text='List of extracted key clauses (auto-renewal, indemnity, termination, etc.)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='risk_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='Risk analysis results with identified risks and their severity'),
        ),
    ]
