"""
Django settings for legalease project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR points to the backend/ directory (parent of legalease/)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load SECRET_KEY from environment variables (stored in .env file)
# config() reads from .env file in the BASE_DIR or from actual environment variables
# The second argument is a default value to use if the variable is not found
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# config() with cast=bool converts string 'True'/'False' to actual boolean values
# Default to False (production-safe) if DEBUG is not set
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS: List of host/domain names that this Django site can serve
# Csv() splits comma-separated values from .env into a Python list
# Example in .env: ALLOWED_HOSTS=localhost,127.0.0.1,yourdomain.com
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT Authentication
    'corsheaders',  # CORS headers for React frontend
    
    # Local apps (our custom apps)
    'contracts',  # Contract analyzer app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'legalease.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'legalease.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# PostgreSQL Database Configuration
# All database credentials are loaded from environment variables for security
# This keeps sensitive information out of the codebase
DATABASES = {
    'default': {
        # PostgreSQL database engine (requires psycopg2-binary package)
        'ENGINE': 'django.db.backends.postgresql',
        
        # Database name - loaded from .env file
        'NAME': config('DB_NAME', default='legalease_db'),
        
        # Database user - typically 'postgres' or a custom user
        'USER': config('DB_USER', default='postgres'),
        
        # Database password - CRITICAL: Never commit this to version control!
        'PASSWORD': config('DB_PASSWORD', default=''),
        
        # Database host - 'localhost' for local development
        # For production, this might be a remote server like 'db.example.com'
        'HOST': config('DB_HOST', default='localhost'),
        
        # Database port - PostgreSQL default is 5432
        # config() with cast=int converts the string to an integer
        'PORT': config('DB_PORT', default='5432', cast=int),
        
        # Connection options (optional, but good for production)
        # CONN_MAX_AGE: Persistent connections (reduces connection overhead)
        # 0 = disable persistent connections, >0 = seconds to keep connection alive
        'CONN_MAX_AGE': 600,  # 10 minutes
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# For production: You'll need to collect static files using: python manage.py collectstatic
# STATIC_ROOT = BASE_DIR / 'staticfiles'  # Uncomment when deploying

# Media files (User uploaded files like PDFs, DOCX)
# https://docs.djangoproject.com/en/5.0/topics/files/
MEDIA_URL = '/media/'  # URL prefix for media files
MEDIA_ROOT = BASE_DIR / 'media'  # Directory where uploaded files are stored

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Keep for admin
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require login for all API endpoints
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Paginate results (10 items per page)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Return JSON responses
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Access token valid for 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,  # Generate new refresh token on each refresh
}

# CORS Settings (Cross-Origin Resource Sharing for React frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server default port
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite development server default port
    "http://127.0.0.1:5173",
]

# Allow credentials (cookies, authorization headers) to be sent
CORS_ALLOW_CREDENTIALS = True

# Celery Configuration (for async task processing)
# Redis connection URL (message broker)
# Default: redis://localhost:6379/0 (localhost, port 6379, database 0)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')

# Where to store task results (optional, we use database instead)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')

# Task result expiration time (results stored for 1 hour, then deleted)
CELERY_RESULT_EXPIRES = 3600  # 1 hour in seconds

# Timezone for scheduled tasks (match Django timezone)
CELERY_TIMEZONE = TIME_ZONE

# Task serialization format (JSON is safer and more portable than pickle)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Accept content types (only JSON for security)
CELERY_ACCEPT_CONTENT = ['json']

# Task time limits
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit: 25 minutes (raises exception)

# Task acknowledgment (don't acknowledge until task is completed)
# If worker crashes, task will be retried
CELERY_TASK_ACKS_LATE = True

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch one task at a time (fair distribution)

# Task routing (optional, for advanced usage)
# CELERY_TASK_ROUTES = {
#     'contracts.tasks.process_contract': {'queue': 'contracts'},
# }

# Production Security Settings (to add later when deploying)
# These are commented out for now, but important for production:
# 
# SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
# SESSION_COOKIE_SECURE = True  # Only send session cookies over HTTPS
# CSRF_COOKIE_SECURE = True  # Only send CSRF cookies over HTTPS
# SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filter
# SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
# X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking (already set in middleware, but can be explicit)
